function Hd = fir_1over256
%FIR_1OVER256 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 11-Dec-2024 20:54:53

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 6144;  % Sampling Frequency

Fpass = 20;               % Passband Frequency
Fstop = 24;               % Stopband Frequency
Dpass = 0.0057563991496;  % Passband Ripple
Dstop = 1e-06;            % Stopband Attenuation
dens  = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
