function Hd = FIR_generalized_equiripple_11000
%FIR_GENERALIZED_EQUIRIPPLE_11000 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 13-Dec-2024 17:05:06

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 6144000;  % Sampling Frequency

N     = 11000;         % Order
Fpass = 20000;         % Passband Frequency
Fstop = 24000;         % Stopband Frequency
Wpass = 1.0115794543;  % Passband Weight
Wstop = 122.16;        % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
