function Hd = FIR_constrained_equiripple_5000
%FIR_CONSTRAINED_EQUIRIPPLE_5000 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 13-Dec-2024 17:06:12

% FIR constrained equiripple Lowpass filter designed using the FIRCEQRIP
% function.

% All frequency values are in Hz.
Fs = 6144000;  % Sampling Frequency

N     = 5000;              % Order
Fc    = 20000;             % Cutoff Frequency
slope = 0;                 % Stopband Slope
Dstop = 7.7983011052e-07;  % Stopband Attenuation
Dpass = 0.058165465269;    % Passband Ripple

% Calculate the coefficients using the FIRCEQRIP function.
b  = firceqrip(N, Fc/(Fs/2), [Dpass, Dstop], 'slope', slope);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
