function Hd = FIR_equiripple_5680
%FIR_EQUIRIPPLE_5680 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 13-Dec-2024 15:20:22

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 6144000;  % Sampling Frequency

Fpass = 20000;             % Passband Frequency
Fstop = 24000;             % Stopband Frequency
Dpass = 0.058165465269;    % Passband Ripple
Dstop = 7.7983011052e-07;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
