function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 13-Dec-2024 17:27:20

Fpass = 20000;    % Passband Frequency
Fstop = 24000;    % Stopband Frequency
Apass = 0.01;     % Passband Ripple (dB)
Astop = 122.16;   % Stopband Attenuation (dB)
Fs    = 6144000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'butter', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);


