function Hd = FIR_equiripple_16043
%FIR_EQUIRIPPLE_16043 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 16-Dec-2024 11:57:57

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 7056000;  % Sampling Frequency

Fpass = 20000;             % Passband Frequency
Fstop = 22050;             % Stopband Frequency
Dpass = 0.00057564620966;  % Passband Ripple
Dstop = 1.2473835142e-05;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
